/** Public host-neutral adapter contracts and validation helpers. */
export {
  cloneFrozen,
  createHarnessAdapterRegistry,
  defineHarnessAdapter,
  defineHarnessDeclaration,
  HARNESS_ASSET_ID_PATTERN,
  invalidAssetId,
  invalidContent,
  nonblank,
  orderHostFeatures,
  PACKAGE_VERSION_PATTERN,
  projectSkillFile,
  projectionFailure,
  projectionSuccess,
  renderMarkdown,
  requireProjectedPath,
  safeHostText,
  sortRecord,
  supportedFeature,
  targetPath,
  unsupportedFeature,
  unsupportedFeatureSupport,
  validLocalMcp,
  validRemoteMcp,
} from './contracts.js';
export {
  HOST_FEATURES,
  type AgentProjectionRequest,
  type ExtensionProjectionRequest,
  type FeatureSupport,
  type HarnessAdapter,
  type HarnessAdapterRegistry,
  type HarnessDeclaration,
  type HarnessScope,
  type HostConfigLocator,
  type HostConfigOperation,
  type HostConfigPlan,
  type HostConfigRequest,
  type HostFeature,
  type HostPackageDeclaration,
  type LocalMcpDeclaration,
  type NeottiaRuntimePackageId,
  type NonEmptyDiagnostics,
  type PackageProjectionRequest,
  type PathAnchor,
  type ProjectedFile,
  type ProjectionDiagnostic,
  type ProjectionDiagnosticCode,
  type ProjectionResult,
  type PromptMetadata,
  type PromptProjectionRequest,
  type ReloadNotice,
  type ReloadRequest,
  type RemoteMcpDeclaration,
  type SkillProjectionRequest,
  type TargetPath,
  type TargetRequest,
} from './types.js';
