name: Call test

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  call:
    uses: dragoscirjan/dragoscirjan.github.io/.github/workflows/docs.yml@main
    with:
      project: call-test-probe
    secrets:
      token: ${{ secrets.GH_TOKEN }}
